---
# tasks file for roles/grafana

- name: Add apt Key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: Add Repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana.list

- name: Install Package
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Start and Enable
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Stop Firewall
  service:
    name: ufw
    state: stopped
    enabled: no
