---
# tasks file for roles/clone_prelimExam_debian

- name: Install Git
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Clone Prelim Exam Repository
  git:
    repo: "{{ git_repo }}"
    dest: "{{ git_dest }}"
    version: "{{ git_version }}"
