---
# tasks file for roles/elasticSearch

- name: Installing Java and Nginx
  apt:
    name:
      - openjdk-11-jdk
      - nginx
    state: latest
    update_cache: yes

- name: Installing APT Transport
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch Key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elasticsearch Repo
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Update Package
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes

- name: Modifying Configuration File
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host'
    line: 'network.host: localhost'

- name: Modify Port in Configuration File
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port'
    line: 'http.port: 9200'

- name: Modify cluster.initial in Configuration File
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'cluster.initial_master_nodes:'
    line: 'cluster.initial_master_nodes: ["{{ ansible_default_ipv4.address }}"]'

- name: Create Service.d Config Directory
  file:
    path: /etc/systemd/system/elasticsearch.service.d
    state: directory
    mode: '0755'

- name: Define TimeoutStartSec
  shell: echo "[Service]\nTimeoutStartSec=180" | sudo tee /etc/systemd/system/elasticsearch.service.d/startup-timeout.conf

- name: Reload daemon
  shell: systemctl daemon-reload

- name: Stop Firewall
  service:
    name: ufw
    state: stopped
    enabled: no

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
