---
# tasks file for roles/httpd_debian

- name: Installing Apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Start Apache2 Service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Creating Virtual Host Directory
  file:
    path: /var/www/lucana_domain
    state: directory
    mode: '0755'

- name: Copy index.html from Files Folder
  copy:
    src: index.html
    dest: /var/www/lucana_domain/index.html
    owner: rlucana-tip
    group: rlucana-tip
    mode: '0755'

- name: Copy lucana_domain.conf to sites-available
  copy:
    src: lucana_domain.conf
    dest: /etc/apache2/sites-available/lucana_domain.conf
    owner: rlucana-tip
    group: rlucana-tip
    mode: '0755'

- name: Enable New Virtual Host
  shell: a2ensite lucana_domain

- name: Disable Default Website
  shell: a2dissite 000-default

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
