---
# tasks file for roles/logstash

- name: Add Elasticsearch Key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Installing APT Transport
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch Repo
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Update Package
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Logstash
  apt:
     name: logstash
     update_cache: yes

- name: Start Logstash
  service:
    name: logstash
    state: started
